---
- hosts: all
  vars_files:
     - vars/default.yml

  tasks:

  - apt: update_cache=yes cache_valid_time=3600

  - apt: upgrade=dist
    notify:
      - reboot

  - name: ensure latest nginx is remove
    apt: pkg=nginx state=absent
    notify:
      - reboot

  - name: ensure latest ntpd is installed
    apt: pkg=ntp state=latest

  - name: Add users
    action: user name={{ item.key }} password={{ item.value.password }} shell={{ item.value.shell }} state={{ item.value.state }} update_password=on_create groups={{ item.value.groups }}
    with_dict: users

  - name: Add public keys
    action: authorized_key user={{ item.key }} key="{{ item.value.public_key  }}"
    with_dict: users

  handlers:

  - name: reboot
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
    notify:
      - wait for reboot

  - name: wait for reboot
    local_action: wait_for host={{ inventory_hostname }}
                  state=started
                  delay=5
    sudo: false
