---
- hosts: all
  tasks:
  - apt: update_cache=yes
  - apt: upgrade=dist
    notify:
      - reboot
  - name: ensure latest ntpd is installed
    apt: pkg=ntp state=latest

  handlers:
  - name: reboot
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
    notify:
      - wait for reboot
  - name: wait for reboot
    local_action: wait_for host={{ inventory_hostname }}
                  state=started
    sudo: false
