---
- hosts: all
  tasks:

  - apt: update_cache=yes cache_valid_time=3600

  - apt: upgrade=dist
    notify:
      - reboot

  - name: ensure latest nginx is remove
    apt: pkg=nginx state=absent
    notify:
      - reboot

  - name: ensure latest ntpd is installed
    apt: pkg=ntp state=latest

  handlers:

  - name: reboot
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
    notify:
      - wait for reboot

  - name: wait for reboot
    local_action: wait_for host={{ inventory_hostname }}
                  delay=30
    sudo: false
