---
users:
  tim:
    shell: /bin/bash
    state: present
    password: $6$rounds=100000$gwCNJ6Z5CscmJn2W$uNlnIPFkEfj95Ub/EfBJTW6vyheC0o1e4YifImmHstHhUdWHEEyQ0icorZU.ts5kOGhPCEN1a3cL4Kwz3gr/D1
    groups: "sudo,tim"
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYpOjASH2qMc4KlYFsPwDukD6K9e1pj3svjLv+OjR6jjUaxaDsPhFZSu18PUrKYXDS2KN9725MOSTr2bAqcMbC2DJpV+otek9wkl3RpVVWX7j4QGFCczvaw1dyvLhMoM+emFo85zjmmMgjFwpcEdOzDIa7CC3DsZO6hGB5Z1Agbjp9ZIPCW9+6IaFptHDfjkJSqd88qh/mgXomdk3NNf0aQDEky5lRP0BJxCH02oiXOfufF+oHZjHD8Bkv+xpz7VoQ8rzWYaaxmLYOp2epxc58t3ILGgzl6FvIzYBW/Tj5qb6a5fvtSGRQyjygE6pfGYcHXYokdfebghEwgOvZiXJsoadOifuvFi6G5TVNrgF7W4BbXx8SO4dXm8Vtsu/kfxLkRU5gjpk7Q1oC8Rib75DpCtRBEOcz23XSjY2gOymYbjZ5DJImoK21I86PnpYr0uy8r2n2nqk2I8sOHNDQDeHb8CGyHT2IXoem+24oWEDkE0vmFjJ3m9/wmqIryMR7yCtkkBXv9fArQF4lU0LnIudMiENFveFh/tJ/qSeC3cM+CSpWf5CVNVCHz7b8Y84+Hy+PfzWvYa5fClJTZPYKsZ7r7XoYI42Hc2xMy/u1oc0Cmy2/0IIX/UrmMhpdxkiHi6jNsrTMRXREfvfR7L4rnQEw3Oi/4LXvrYOekT+sUJXl0Q== timbuchwaldt@tbu-mbp.local


